# Generated by Django 2.2.6 on 2019-10-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='alamat',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='existing',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='gaji',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='jenis_kelamin',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='occupation',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
