# Generated by Django 2.2.6 on 2019-10-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0002_auto_20191030_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='jenis_kelamin',
            field=models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], default='L', max_length=1),
        ),
    ]
