# Generated by Django 2.2.6 on 2019-10-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_auto_20191030_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='occupation',
            field=models.CharField(choices=[('n', 'Non-Fix'), ('f', 'Fix')], default='n', max_length=1),
        ),
    ]
