# Generated by Django 2.2.6 on 2019-10-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_auto_20191030_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kendaraan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('harga', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='kendaraan',
            field=models.ManyToManyField(to='customerapp.Kendaraan'),
        ),
    ]
