# Generated by Django 2.2.6 on 2019-10-30 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0005_auto_20191030_1047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kendaraan',
            new_name='Vehicle',
        ),
    ]
